<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

  <!-- Attach a thin AprilTag "card" to parent_link -->
  <xacro:macro name="attach_apriltag_card" params="
      parent_link
      tag_size:=0.02              
      extra_len:=0.03             
      tag_thickness:=0.001
      xyz:='0 0 0.02'
      rpy:='0 0 0'
      link_name:='${parent_link}_apriltag'
      mass:=0.01
      texture_path:='package://sirgas_description/meshes/Apriltag36_11_00000/materials/textures/tag36_11_00000.png'
      add_back_visual:=false
      back_epsilon:=0.0005">
    <xacro:property name="size_x" value="${tag_size}"/>             
    <xacro:property name="size_y" value="${tag_size + extra_len}"/> 
    <xacro:property name="size_z" value="${tag_thickness}"/>
    <link name="${link_name}">
      <!-- front face -->
      <visual>
        <origin xyz="${xyz}" rpy="${rpy}"/>
        <geometry>
          <box size="${size_x} ${size_y} ${size_z}"/>
        </geometry>
        <material name="${link_name}_front_tex">
          <texture filename="${texture_path}"/>
        </material>
      </visual>

      <!-- optional back face for RViz (flipped 180 deg around Y) -->
      <xacro:if value="${add_back_visual}">
        <visual>
          <origin xyz="${xyz}" rpy="0 3.141592653589793 0"/>
          <geometry>
            <box size="${tag_size} ${tag_size} ${tag_thickness}"/>
          </geometry>
          <material name="${link_name}_back_tex">
            <texture filename="${texture_path}"/>
          </material>
        </visual>
      </xacro:if>

      <collision>
        <origin xyz="${xyz}" rpy="${rpy}"/>
        <geometry>
           <box size="${size_x} ${size_y} ${size_z}"/>
        </geometry>
      </collision>

      <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="${mass}"/>
          <xacro:property name="Ixx" value="${mass*((size_y*size_y + size_z*size_z)/12.0)}"/>
          <xacro:property name="Iyy" value="${mass*((size_x*size_x + size_z*size_z)/12.0)}"/>
          <xacro:property name="Izz" value="${mass*((size_x*size_x + size_y*size_y)/12.0)}"/>
          <inertia ixx="${Ixx}" iyy="${Iyy}" izz="${Izz}" ixy="0" ixz="0" iyz="0"/>
        </inertial>
    </link>

    <joint name="${link_name}_fixed" type="fixed">
      <parent link="${parent_link}"/>
      <child link="${link_name}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <gazebo reference="${link_name}">
      <material>
        <double_sided>1</double_sided>
        <ambient>0.6 0.6 0.6 1</ambient>
        <diffuse>1 1 1 1</diffuse>
        <emissive>0.05 0.05 0.05 1</emissive>
        <pbr>
          <metal>
            <albedo_map>package://sirgas_description/meshes/Apriltag36_11_00000/materials/textures/tag36_11_00000.png</albedo_map>
            <roughness>1.0</roughness>
            <metalness>0.0</metalness>
          </metal>
        </pbr>
      </material>
    </gazebo>

  </xacro:macro>
</robot>