controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

forward_velocity_controller:
  ros__parameters:
    # Only control the master joint - mimic joints will follow automatically
    joints:
      - pb_starter_joint
    interface_name: velocity
    state_interfaces:
      - position
      - velocity