pba_controller_manager:
  ros__parameters:
    update_rate: 100

    pba_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

pba_joint_state_broadcaster:
  ros__parameters:
    state_publish_rate: 100.0
    joints:
      - pb_starter_joint
      - pb_first_joint  
      - pb_second_joint
      - pb_third_joint

velocity_controller:
  ros__parameters:
    joints:
      - pb_starter_joint
    interface_name: velocity
    state_interfaces:
      - position
      - velocity
      - effort