# combined_controller_manager:
#   ros__parameters:
#     update_rate: 500  # Hz

#     # --- UR20 Starter Controllers ---
#     ur20_joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

#     io_and_status_controller:
#       type: ur_controllers/GPIOController

#     speed_scaling_state_broadcaster:
#       type: ur_controllers/SpeedScalingStateBroadcaster

#     ur20_joint_trajectory_controller: # Renamed for clarity
#       type: joint_trajectory_controller/JointTrajectoryController

#     scaled_joint_trajectory_controller:
#       type: ur_controllers/ScaledJointTrajectoryController

#     ur20_forward_velocity_controller: # Renamed for clarity
#       type: velocity_controllers/JointGroupVelocityController

#     forward_position_controller:
#       type: position_controllers/JointGroupPositionController
      
#     # --- PBA Controllers ---
#     pba_joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

#     pba_velocity_controller: # Renamed for clarity
#       type: velocity_controllers/JointGroupVelocityController

#     # --- Gripper Controllers ---
#     gripper_joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

#     gripper_position_controller:
#       type: position_controllers/JointGroupPositionController

# # --------------------------------------------------------------------------------------------------
# # Controller configurations at ROOT level (not nested)
# # --------------------------------------------------------------------------------------------------

# # --- UR20 Starter Configurations ---
# ur20_joint_state_broadcaster:
#   ros__parameters:
#     state_publish_rate: 100.0

# speed_scaling_state_broadcaster:
#   ros__parameters:
#     state_publish_rate: 100.0

# ur20_joint_trajectory_controller:
#   ros__parameters:
#     joints:
#       - ur20_starter/shoulder_pan_joint
#       - ur20_starter/shoulder_lift_joint
#       - ur20_starter/elbow_joint
#       - ur20_starter/wrist_1_joint
#       - ur20_starter/wrist_2_joint
#       - ur20_starter/wrist_3_joint
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
#     state_publish_rate: 100.0
#     action_monitor_rate: 20.0
#     allow_partial_joints_goal: false
#     constraints:
#       stopped_velocity_tolerance: 0.2
#       goal_time: 0.0
#       shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
#       shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
#       elbow_joint: { trajectory: 0.2, goal: 0.1 }
#       wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
#       wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
#       wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

# scaled_joint_trajectory_controller:
#   ros__parameters:
#     joints:
#       - ur20_starter/shoulder_pan_joint
#       - ur20_starter/shoulder_lift_joint
#       - ur20_starter/elbow_joint
#       - ur20_starter/wrist_1_joint
#       - ur20_starter/wrist_2_joint
#       - ur20_starter/wrist_3_joint
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
#       - effort
#     speed_scaling_interface_name: ""
#     state_publish_rate: 100.0
#     action_monitor_rate: 20.0
#     allow_partial_joints_goal: false
#     constraints:
#       stopped_velocity_tolerance: 0.2
#       goal_time: 0.0
#       shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
#       shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
#       elbow_joint: { trajectory: 0.2, goal: 0.1 }
#       wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
#       wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
#       wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

# ur20_forward_velocity_controller:
#   ros__parameters:
#     joints:
#       - ur20_starter/shoulder_pan_joint
#       - ur20_starter/shoulder_lift_joint
#       - ur20_starter/elbow_joint
#       - ur20_starter/wrist_1_joint
#       - ur20_starter/wrist_2_joint
#       - ur20_starter/wrist_3_joint
#     interface_name: velocity

# ur20_forward_position_controller:
#   ros__parameters:
#     joints:
#       - ur20_starter/shoulder_pan_joint
#       - ur20_starter/shoulder_lift_joint
#       - ur20_starter/elbow_joint
#       - ur20_starter/wrist_1_joint
#       - ur20_starter/wrist_2_joint
#       - ur20_starter/wrist_3_joint
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
#       - effort

# # --- PBA Configurations ---
# pba_joint_state_broadcaster:
#   ros__parameters:
#     state_publish_rate: 100.0
#     joints:
#       - pb_starter_joint
#       - pb_first_joint  
#       - pb_second_joint
#       - pb_third_joint

# pba_velocity_controller:
#   ros__parameters:
#     joints:
#       - pb_starter_joint
#     interface_name: velocity
#     state_interfaces:
#       - position
#       - velocity
#       - effort

# # --- Gripper Configurations ---
# gripper_joint_state_broadcaster:
#   ros__parameters:
#     state_publish_rate: 100.0
#     joints:
#       - finger_joint
#       - left_inner_knuckle_joint
#       - left_inner_finger_joint
#       - right_inner_knuckle_joint
#       - right_inner_finger_joint
#       - right_outer_knuckle_joint

# gripper_position_controller:
#   ros__parameters:
#     joints:
#       - finger_joint
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity

combined_controller_manager:
  ros__parameters:
    update_rate: 500  # Hz
    use_sim_time: true

    # --- Panda Controllers ---

    panda_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
  
    panda_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    hand_controller:
      type: position_controllers/GripperActionController

    # --- PBA Controllers ---
    pba_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    pba_velocity_controller: # Renamed for clarity
      type: velocity_controllers/JointGroupVelocityController

# --------------------------------------------------------------------------------------------------
# Controller configurations at ROOT level (not nested)
# --------------------------------------------------------------------------------------------------

# --- Panda Configurations ---
panda_joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true
    state_publish_rate: 100.0
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7

panda_arm_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
hand_controller:
  ros__parameters:
    use_sim_time: true
    joint: panda_finger_joint1

# --- PBA Configurations ---
pba_joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true
    state_publish_rate: 100.0
    joints:
      - pb_starter_joint
      - pb_first_joint  
      - pb_second_joint
      - pb_third_joint

pba_velocity_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - pb_starter_joint
    interface_name: velocity
    state_interfaces:
      - position
      - velocity
      - effort
