# Default initial positions for panda_pba_robots's ros2_control fake system
use_sim_time: true
initial_positions:
  panda_finger_joint1: 0
  panda_finger_joint2: 0
  panda_joint1: 0
  panda_joint2: 0
  panda_joint3: 0
  panda_joint4: 0
  panda_joint5: 0
  panda_joint6: 0
  panda_joint7: 0